### ISSUE TITLE
DEV_TYPE_COUNT_PHYSICAL has been removed upstream

### ISSUE THREAD

**Issue by mgdde** [okyeron/neotrellis-monome#5]
The line
#define DEV_TYPE_COUNT_PHYSICAL 4
has been removed from norns/matron/src/device/device_common.h and that breaks compilation. As a quick fix I added the above line to device_monitor.c locally and the build worked.

**Comment by okyeron** [comment]
Apologies for not checking in here much.

Which compilation does/did that break? Is this still an issue with the latest norns updates?
